### ISSUE TITLE
Qspy.exe being quarantined by windows

### ISSUE THREAD

**Issue by aguirrem** [QuantumLeaps/qtools#17]
I am unaware of any other reports but I am currently experiencing issues with Qspy where it is being removed and quarantined by windos malware detection system.
![image](https://github.com/QuantumLeaps/qtools/assets/1304511/117293b4-1a25-4c74-92f6-05caf7d774d5)

**Comment by quantum-leaps** [comment]
Hi [aguirrem](https://github.com/aguirrem),

Thank you for reporting the issue.

This was discussed a week ago on the Free Support Forum, see discussion "Windows Blocking QSPY":

https://sourceforge.net/p/qpc/discussion/668726/thread/e0410aa30b/

Specifically, the resolution of the problem is described in this post:

https://sourceforge.net/p/qpc/discussion/668726/thread/e0410aa30b/#5501

Please download the updated Windows installer (qp-windows_7.3.0a.exe) and re-install QP-bundle 7.3.0.

Best regards,
   Miro

-- 
Miro Samek, Ph.D.
Quantum Leaps, LLC

[miro@state-machine.com](mailto:miro@state-machine.com)
+1-919-360-5668

**Comment by quantum-leaps** [comment]
The issue of `qspy.exe` being flagged by Microsoft Threat Protection has been resolved. Specifically, the executable has been re-built with the Microsoft Visual Studio C++ compiler, which does not trigger any virus alerts. Additionally, the executable was checked with VirusTotal.com. The issue is therefore closed.
